### ISSUE TITLE
Bug in `wrong_args_for_callable()` causes firewall-applet to crash (regression introduced in 2.1.0)

### ISSUE THREAD

**Issue by silverhook** [firewalld/firewalld#1310]
### What happened

After update to 2.1.x `firewall-applet` constantly crashes on start, with the following error.

```py
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/firewall/client.py", line 3488, in _signal_receiver
    cb(*cb_args)
  File "/usr/bin/firewall-applet", line 1018, in connection_established
    self.update_active_zones()
  File "/usr/bin/firewall-applet", line 741, in update_active_zones
    escape(binding.format(zone=zone, entry=connection_name)), self
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'vnos'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/firewall/client.py", line 46, in _impl
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/firewall/client.py", line 3490, in _signal_receiver
    if firewall.functions.wrong_args_for_callable(cb, *cb_args):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/firewall/functions.py", line 669, in wrong_args_for_callable
    inspect.bind(fcn, *a, **kw)
    ^^^^^^^^^^^^
AttributeError: module 'inspect' has no attribute 'bind'
```

### What you expected to happen

Not to crash :)

### How to reproduce it (as minimally and precisely as possible)

1. install firewalld 2.1.x
2. start `firewall-applet`

### Anything else we need to know?

The bug was introduced in https://github.com/firewalld/firewalld/commit/160ac584aea2ce8de2c10c5db687ef7c5bbda961 (that is the only function that commit touched) and apparently the problem is that

> According to the [python documentation](https://docs.python.org/3.7/library/inspect.html#inspect.Signature.bind) for the inspect module, `bind()` is not a top-level function but a method for the `Signature` type. The call `inspect.bind()` will fail with an `AttributeError` because the `inspect` module object does not have an attribute called `bind`.

More info:
https://forum.endeavouros.com/t/firewall-applet-constantly-crashes/51358/8?u=hook

### Firewalld Version

2.1.1

### Firewalld Backend

nftables

### Linux distribution

EndeavourOS

### Linux kernel version

6.7.5-zen1-1-zen

### Other information

Downgrading back to 2.0.x is a work-around.

**Comment by thom311** [comment]
thanks for the report.
